#release configuration
#Fri Feb 13 13:25:10 CET 2026
completedPhase=check-poms
exec.additionalArguments=-Dmaven.deploy.skip\=true
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.no.ssb.maskinporten\:maskinporten-guardian.developerConnection=scm\:git\:https\://github.com/${github.repository}.git
project.scm.no.ssb.maskinporten\:maskinporten-guardian.tag=1.4.13
project.scm.no.ssb.maskinporten\:maskinporten-guardian.url=https\://github.com/${github.repository}
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:https\://github.com/statisticsnorway/maskinporten-guardian.git
