apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  name: alert-maskinporten-guardian
  namespace: dftjen
  labels:
    team: dftjen
spec:
  groups:
    - name: dftjen
      rules:
        - alert: High number of errors
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="maskinporten-guardian",level=~"Error"}[3m])) / sum by (app, namespace) (rate(log_messages_total{app="maskinporten-guardian"}[3m]))) > 10
          for: 3m
          annotations:
            title: "High number of errors logged"
            consequence: "There can be different causes for errors, check logs for cause and evaluation of consequences."
            action: "`kubectl describe pod -l app=maskinporten-guardian -n dapla-stat` -> `kubectl logs <podname>`"
          labels:
            service: maskinporten-guardian
            namespace: dftjen
            alertmanager_custom_config: dftjen
            alert_type: custom
            severity: critical

        - alert: Guardian is unavailable
          expr: kube_deployment_status_replicas_available{deployment="maskinporten-guardian"} == 0
          for: 1m
          annotations:
            title: "Maskinporten Guardian is unavailable"
            consequence: "Service is unavailable to users. "
          labels:
            service: maskinporten-guardian
            namespace: dftjen
            alertmanager_custom_config: dftjen
            alert_type: custom
            severity: critical
