apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: maskinporten-guardian
  namespace: dapla-stat
  labels:
    team: dapla-stat
spec:
  image: "{{ image }}"  # Injected from the GitHub Action
  port: 10310
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 1000m
      memory: 500Mi

  ingresses:
    - https://guardian.intern.ssb.no

  accessPolicy:
    outbound:
      external:
        - host: "auth.ssb.no"
        - host: "keycloak.prod-bip-app.ssb.no"
        - host: "maskinporten.no"
        - host: "sky.maskinporten.no"

  liveness:
    path: /health/liveness
    port: 10310
  readiness:
    path: /health/readiness
    port: 10310
  startup:
    path: /health/readiness
    port: 10310

  env:
    - name: MICRONAUT_CONFIG_FILES
      value: /conf/bootstrap-prod.yml,/conf/application-prod.yml,/conf/auth/maskinporten-clients.yml
    - name: LOGBACK_CONFIGURATION_FILE
      value: /conf/logback-prod.xml

  filesFrom:
    - configmap: guardian-application-prod-configmap
      mountPath:  /conf
    - configmap: maskinporten-clients-prod-configmap
      mountPath:  /conf/auth

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: maskinporten-guardian-application-yaml-configmap
  namespace: dapla-stat
  labels:
    team: dapla-stat
data:
  bootstrap-prod.yml: |-
    micronaut:
      application:
        name: maskinporten-guardian
      config-client:
        enabled: true

  application-prod.yml: |-
    micronaut:
      application:
        name: maskinporten-guardian
      server:
        port: 10310
      
      security:
        enabled: true
        token:
          name-key: preferred_username
          jwt:
            signatures:
              jwks:
                keycloak-prod:
                  url: 'https://keycloak.prod-bip-app.ssb.no/auth/realms/ssb/protocol/openid-connect/certs'
                auth-prod:
                  url: 'https://auth.ssb.no/realms/ssb/protocol/openid-connect/certs'

    endpoints:
      prometheus:
        sensitive: false
    
    gcp:
      project-id: ssb-team-dapla
    
    services:
      secrets:
        impl: GCP
    
    certificates:
      ssb-maskinporten-virksomhetssertifikat:
        certificate-secret-id: ssb-prod-seid2-p12-certificate
        certificate-passphrase-secret-id: ssb-prod-seid2-p12-passphrase
        certificate-keystore-entry-alias: statistisk sentralbyrå
