POST {{maskinporten-guardian-baseurl}}/access-token
Content-Type: application/json
Authorization: Bearer {{dapla-access-token}}

{
  "maskinportenClientId": "{{mp-client-id-test}}",
  "scopes": [
    "some:scope1"
  ]
}

###

POST {{maskinporten-guardian-baseurl}}/access-token
Content-Type: application/json
Authorization: Bearer {{dapla-access-token}}

{
  "maskinportenClientId": "{{mp-client-id-freg}}",
  "scopes": [
    "folkeregister:deling/offentligmedhjemmel"
  ]
}

###

POST {{maskinporten-guardian-baseurl}}/access-token
Content-Type: application/json
Authorization: Bearer {{dapla-access-token}}

{
  "maskinportenClientId": "{{mp-client-id-skatt-naering}}",
  "scopes": [
    "skatteetaten:naeringsspesifikasjon"
  ]
}

###

POST {{maskinporten-guardian-baseurl}}/client/{{mp-client-id-test}}
Content-Type: application/json

{
  "scopes": [
    "some:scope1"
  ]
}

###

GET {{maskinporten-guardian-baseurl}}/health/readiness

###

GET {{maskinporten-guardian-baseurl}}/health/liveness

###

GET {{maskinporten-guardian-baseurl}}/prometheus

###

GET {{maskinporten-guardian-baseurl}}/metrics
