micronaut:
  application:
    name: maskinporten-guardian
  server:
    port: 10310
    cors:
      enabled: true
      configurations:
        localhost-forwarding:
          allowedOrigins:
            - http://localhost:10310
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /openapi/**

  security:
    intercept-url-map:
      - pattern: /**/openapi/**
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      name-key: preferred_username
      jwt:
        signatures:
          jwks:
            auth-prod:
              url: 'https://auth.ssb.no/realms/ssb/protocol/openid-connect/certs'
            auth-test:
              url: 'https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs'

endpoints:
  prometheus:
    sensitive: false

services:
  secrets:
    impl: LOCAL
    override-values:
      ssb-dev-p12-passphrase: pass123
    override-files:
      ssb-dev-p12-certificate: src/test/resources/virksomhetssertifikat-test.p12

certificates:
  ssb-maskinporten-virksomhetssertifikat:
    certificate-secret-id: ssb-dev-p12-certificate
    certificate-passphrase-secret-id: ssb-dev-p12-passphrase
    certificate-keystore-entry-alias: testalias

maskinporten:
  clients:
    7ea43b76-6b7d-49e8-af2b-4114ebb66c80:
      description: client used for testing
      audience: https://ver2.maskinporten.no/
      authorized-users:
        - kjell.fjell@ssb.no
