name: Deploy alerts
run-name: Deploy alerts for Maskinporten Guardian to test and prod

on:
  push:
    branches:
      - master
    paths:
      - '.nais/alerts.yaml'
      - '.github/workflows/alert-deploy.yml'
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  test-deploy:
    name: Deploy alerts to test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to test
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: test
          RESOURCE: .nais/alerts.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
      - name: Deploy AlertManagerConfig
        uses: statisticsnorway/nais-alert-config@0.0.1
        with:
          cluster: "test"

  prod-deploy:
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/alerts.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
      - name: Deploy AlertManagerConfig
        uses: statisticsnorway/nais-alert-config@0.0.1
        with:
          cluster: "prod"