name: Deploy to NAIS
on:
  push:
    branches:
      - deploy

  workflow_call:
    inputs:
      image:
        description: Image on the form <REGISTRY>/<REPOSITORY>/<IMAGE_NAME>
        required: true
        type: string
      cluster:
        description: NAIS cluster environment
        required: true
        type: string
      nais-config-path:
        description: Path to the NAIS configuration file
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to NAIS cluster
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DAPLA_BOT_APP_ID }}
          private-key: ${{ secrets.DAPLA_BOT_PRIVATE_KEY }}

      - name: Configure Git user
        run: |
          git config user.email "dapla-bot[bot]"
          git config user.name "143391972+dapla-bot[bot]@users.noreply.github.com"

      - uses: actions/checkout@v4
        name: Retrieve protected configuration
        with:
          repository: "statisticsnorway/data-collector-core"
          path: "protected-config"
          ref: "main"
          token: ${{ steps.app-token.outputs.token }}

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.nais-config-path }}
          VAR: image=${{ inputs.image }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443