name: Deploy to NAIS
on:
  push:
    branches:
      - deploy

  workflow_call:
    inputs:
      image:
        description: Image on the form <REGISTRY>/<REPOSITORY>/<IMAGE_NAME>
        required: true
        type: string
      cluster:
        description: NAIS cluster environment
        required: true
        type: string
      nais-config-path:
        description: Path to the NAIS configuration file
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to NAIS cluster
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DAPLA_BOT_APP_ID }}
          private-key: ${{ secrets.DAPLA_BOT_PRIVATE_KEY }}
          owner: statisticsnorway
          repositories: maskinporten-guardian, dapla-stat-iac

      # Set inputs based on the event type
      - name: Set inputs for push event
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "cluster=prod" >> $GITHUB_ENV
          echo "nais_config_path=.nais/prod.yaml" >> $GITHUB_ENV
          echo "image=europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-stat-docker/maskinporten-guardian:latest" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        name: Retrieve protected configuration
        with:
          repository: "statisticsnorway/dapla-stat-iac"
          path: "app-config"
          token: ${{ steps.app-token.outputs.token }}
          sparse-checkout: |
            apps/nais/maskinporten-guardian/${{ inputs.cluster || env.cluster }}

      - name: Set app_config environment variable
        run: |
          app_config_dir="app-config/apps/nais/maskinporten-guardian/${{ inputs.cluster || env.cluster }}"
          ls -la ${app_config_dir}
          tree -L 6 app-config
          echo ${app_config_dir}
          ls -la ${app_config_dir}
          cat ${app_config_dir}/bootstrap-${{ inputs.cluster || env.cluster }}.yml
          echo "app_config=${app_config_dir}" >> $GITHUB_ENV

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster || env.cluster }}
          RESOURCE: .nais/${{ inputs.cluster || env.cluster }}.yaml, ${{ env.app_config }}/bootstrap-${{ inputs.cluster || env.cluster }}.yml, ${{ env.app_config }}/application-${{ inputs.cluster || env.cluster }}.yml
          VAR: image=${{ inputs.image || env.image }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443