name: Publish release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Publish GitHub release
        id: fetch-id
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"\
          /repos/statisticsnorway/maskinporten-guardian/releases\
          | jq -r 'map(select(.draft == true)) | first | .id')
          echo "id=${id}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}