name: Publish release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "Makefile"
      - ".mvn"
      - ".gitignore"
  workflow_dispatch:

jobs:
  publish-release:
    if: |
      (github.head_ref == 'release' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Publish GitHub release
        id: fetch-id
        run: |
          tag=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"\
          /repos/statisticsnorway/maskinporten-guardian/releases\
          | jq -r 'map(select(.draft == true)) | first | .tag_name')
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          gh release edit $tag --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  #deploy:
  #  name: Deploy to NAIS
  #  needs: publish-release
  #  uses: ./.github/workflows/build-deploy.yml
  #  with:
  #    tag: 