name: Publish release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "Makefile"
      - ".mvn"
      - ".gitignore"
  workflow_dispatch:

jobs:
  publish-release:
    if: |
      (github.head_ref == 'release' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Fetch id of the latest release draft
        id: fetch-id
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"\
          /repos/statisticsnorway/maskinporten-guardian/releases\
          | jq -r 'map(select(.draft == true)) | first | .id')
          echo "id=${id}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.fetch-id.outputs.id }}
