name: Publish release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "Makefile"
      - ".mvn"
      - ".gitignore"
  workflow_dispatch:

jobs:
  publish-release:
    if: |
      (github.head_ref == 'release' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Fetch tag of the latest release draft
        id: fetch-tag
        run: |
          tag="$(gh release list -R ${{ github.repository }} --limit 1 | awk -F '\t' '{if (match($2, "Draft")) print $3}')"
          if [ ! -z "$tag" ]; then
            echo "Latest draft tag is not a draft release!"
            exit 1
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch release information from GitHub API
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/repos/${{ github.repository }}/releases/tags/${{steps.fetch-tag.outputs.tag}}
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"} }'

      - name: Publish GitHub release
        uses: eregon/publish-release@v1
        with:
          release_id: ${{ fromJson(env.fetch-api-data).id }}